const Slova01 = {
    a: { veliko: "radno-01.png", malo: "radno-02.png", audio1: "01 nase novo slovo je slovo A kazi A.mp3", audio2: "02 ovo je nase malo slovo A kazi A.mp3", delay: 8000 },
    b: { veliko: "radno-03.png", malo: "radno-04.png", audio1: "", audio2: "", delay: 8000 },
    v: { veliko: "radno-05.png", malo: "radno-06.png", audio1: "", audio2: "", delay: 8000 },
    g: { veliko: "radno-07.png", malo: "radno-08.png", audio1: "", audio2: "", delay: 8000 },
    d: { veliko: "radno-09.png", malo: "radno-10.png", audio1: "", audio2: "", delay: 8000 },
    dj: { veliko: "radno-11.png", malo: "radno-12.png", audio1: "", audio2: "", delay: 8000 },
    e: { veliko: "radno-13.png", malo: "radno-14.png", audio1: "01 nase novo slovo je slovo E kazi E.mp3", audio2: "02 a ovo je nase malo slovo E kazi E.mp3", delay: 8000 },
    zh: { veliko: "radno-15.png", malo: "radno-16.png", audio1: "", audio2: "", delay: 8000 },
    z: { veliko: "radno-17.png", malo: "radno-18.png", audio1: "", audio2: "", delay: 8000 },
    i: { veliko: "radno-19.png", malo: "radno-20.png", audio1: "01 nase novo slovo je slovo I kazi I.mp3", audio2: "02 ovo je nase malo slovo I kazi I.mp3", delay: 8000 },
    j: { veliko: "radno-21.png", malo: "radno-22.png", audio1: "01 nase novo slovo je slovo U kazi U.mp3", audio2: "02 ovo je nase malo slovo U kazi U.mp3", delay: 8000 },
    k: { veliko: "radno-23.png", malo: "radno-24.png", audio1: "12 nase novo slovo je slovo N kazi N.mp3", audio2: "13 a ovo je nase malo slovo N kazi N.mp3", delay: 8000 },
    l: { veliko: "radno-25.png", malo: "radno-26.png", audio1: "12 nase novo slovo je slovo N kazi N.mp3", audio2: "13 a ovo je nase malo slovo N kazi N.mp3", delay: 8000 },
    lj: { veliko: "radno-27.png", malo: "radno-28.png", audio1: "", audio2: "", delay: 8000 },
    m: { veliko: "radno-29.png", malo: "radno-30.png", audio1: "12 nase novo slovo je slovo M kazi M.mp3", audio2: "13 ovo je nase malo slovo M kazi M.mp3", delay: 8000 },
    n: { veliko: "radno-31.png", malo: "radno-32.png", audio1: "12 nase novo slovo je slovo N kazi N.mp3", audio2: "13 a ovo je nase malo slovo N kazi N.mp3", delay: 8000 },
    nj: { veliko: "radno-33.png", malo: "radno-34.png", audio1: "", audio2: "", delay: 8000 },
    o: { veliko: "radno-35.png", malo: "radno-36.png", audio1: "12 nase novo slovo je slovo O kazi O.mp3", audio2: "13 a ovo je nase malo slovo O kazi O.mp3", delay: 8000 },
    p: { veliko: "radno-37.png", malo: "radno-38.png", audio1: "12 nase novo slovo je slovo N kazi N.mp3", audio2: "13 a ovo je nase malo slovo N kazi N.mp3", delay: 8000 },
    r: { veliko: "radno-39.png", malo: "radno-40.png", audio1: "01 nase novo slovo je slovo R kazi R.mp3", audio2: "02 ovo je nase malo slovo R kazi R.mp3", delay: 8000 },
    s: { veliko: "radno-41.png", malo: "radno-42.png", audio1: "12 nase novo slovo je slovo S kazi S.mp3", audio2: "13 a ovo je nase malo slovo S kazi S.mp3", delay: 8000 },
    t: { veliko: "radno-43.png", malo: "radno-44.png", audio1: "01 nase novo slovo je slovo T kazi T.mp3", audio2: "02 ovo je nase malo slovo T kazi T.mp3", delay: 8000 },
    cc: { veliko: "radno-45.png", malo: "radno-46.png", audio1: "", audio2: "", delay: 8000 },
    u: { veliko: "radno-47.png", malo: "radno-48.png", audio1: "01 nase novo slovo je slovo U kazi U.mp3", audio2: "02 ovo je nase malo slovo U kazi U.mp3", delay: 8000 },
    f: { veliko: "radno-49.png", malo: "radno-50.png", audio1: "", audio2: "", delay: 8000 },
    h: { veliko: "radno-51.png", malo: "radno-52.png", audio1: "", audio2: "", delay: 8000 },
    c: { veliko: "radno-53.png", malo: "radno-54.png", audio1: "", audio2: "", delay: 8000 },
    ch: { veliko: "radno-55.png", malo: "radno-56.png", audio1: "", audio2: "", delay: 8000 },
    dz: { veliko: "radno-57.png", malo: "radno-58.png", audio1: "", audio2: "", delay: 8000 },
    sh: { veliko: "radno-59.png", malo: "radno-60.png", audio1: "12 nase novo slovo je slovo N kazi N.mp3", audio2: "13 a ovo je nase malo slovo N kazi N.mp3", delay: 8000 }
}

export default Slova01
